### ISSUE TITLE
Is the demo a joke?

### ISSUE THREAD

**Issue by limelect** [lminuti/FontIconEditor#1]
Is the demo a joke?
Nothing in it

**Comment by HemulGM** [comment]
The demo demonstrates the work. There are buttons and an ImageList. The meaning of the package in the Add Images Wizard. It must first be installed.

**Comment by HemulGM** [comment]
> Is the demo a joke?
> Nothing in it

The demo demonstrates the work. There are buttons and an ImageList. The meaning of the package in the Add Images Wizard. It must first be installed.

**Comment by lminuti** [comment]
> Is the demo a joke?
> Nothing in it

Try the last commit. I hope the demo is more clear.
